### ISSUE TITLE
Put your project in the EnTT in Action list

### ISSUE THREAD

**Issue by skypjack** [alohaeee/DungeonSlayer#1]
Hi, sorry to bother you, I'm the author of `EnTT`.

I found your project and I think it's interesting in many ways.
Probably you already know that but I'm also trying to give the users of `EnTT` a few examples from which to take inspiration when they move their first steps. Since your project uses the latest version of the library, I think it can be an excellent candidate!

I'm asking this because I usually prefer to ping authors before referring to other projects.
What do you think about putting your repo in [the list of projects](https://github.com/skypjack/entt/wiki/EnTT-in-Action) _made with `EnTT`_?
If it's fine for you, you can just close the issue with a :+1: I'd be glad to have your project in that list.

Thanks anyway. :+1:

**Comment by alohaeee** [comment]
👍
